### ISSUE TITLE
Facing Problem while installing icingabeat

### ISSUE THREAD

**Issue by ramya397** [Icinga/icingabeat#15]
Hi

i am getting bellow error while doing "make"

go build
main.go:6:2: cannot find package "github.com/elastic/beats/libbeat/beat" in any of:
	/usr/lib/go-1.6/src/github.com/elastic/beats/libbeat/beat (from $GOROOT)
	($GOPATH not set)
main.go:8:2: cannot find package "github.com/icinga/icingabeat/beater" in any of:
	/usr/lib/go-1.6/src/github.com/icinga/icingabeat/beater (from $GOROOT)
	($GOPATH not set)
vendor/github.com/elastic/beats/libbeat/scripts/Makefile:74: recipe for target 'icingabeat' failed
make: *** [icingabeat] Error 1

and i have set bellow  variable in bashrc file

export GOROOT="/usr/lib/go-1.6"
export GOPATH="/usr/lib/go-1.6"
export PATH="$GOROOT/bin:$PATH"

i have installed go1.6

please help

**Comment by bobapple** [comment]
@ramya397 the project currently requires go 1.7, future versions will require go 1.9
Please feel free to reopen the issue if it still occurs with newer go versions
