### ISSUE TITLE
Update Icingabeat to Elastic Stack 6.x (libbeat, Kibana dashboards)

### ISSUE THREAD

**Issue by dnsmichi** [Icinga/icingabeat#19]
Beats 6.x now use their own Kibana API to automatically setup dashboards.

https://www.elastic.co/guide/en/beats/filebeat/6.0/filebeat-configuration.html
https://www.elastic.co/guide/en/beats/filebeat/6.0/load-kibana-dashboards.html

## Context 

The old 5.x way using the import_dashboards script does not work anymore.

```
/usr/share/icingabeat/scripts/import_dashboards -dir /tmp/icingabeat-dashboards-1.1.1 -es http://127.0.0.1:9200
```

gives a 400 bad request. Seems you cannot use Icingabeat 5.3.2 with Elastic Stack 6.x.

The script removal in 6.x is mentioned here: https://github.com/elastic/beats/issues/3740#issuecomment-331867065

## Possible Solution

- Upgrade to libbeat 6.0
- Include setup configuration details (should be coming from libbeat itself)
- Regenerate Kibana dashboards
- Create new release builds

**Comment by bobapple** [comment]
Fixed in [Branch 6.1](https://github.com/Icinga/icingabeat/tree/6.1)
