### ISSUE TITLE
Icingabeat v6.1.1 is trying to send more than 1000 different fields

### ISSUE THREAD

**Issue by widhalmt** [Icinga/icingabeat#20]
## Expected Behavior

Icingabeat should write only a very small set of different fields to Elasticsearch.

## Current Behavior

* Some events from Icingabeat are sent as expected. Giving a total of about 190 distinct fields.
* About every 5 Minutes Elasticsearch refuses a bulk request which would add enough new fields to get over 1000 distinct fields in the index.

## Possible Solution

Review what Icingabeat is sending to Elasticsearch and restrict the overall count of distinct fields.

## Steps to Reproduce (for bugs)
1. Start Icingabeat 6.1.1 with the following configuration to send data to Elastic Stack 6.1.2
<pre>
icingabeat:
  host: "icinga01.example.com"
  port: 5665
  user: "logstash"
  password: "supersecret"
  ssl.verify: false
  eventstream.types:
    - CheckResult
    - StateChange
  eventstream.filter: ""
  eventstream.retry_interval: 10s 
  statuspoller.interval: 60s 
setup.kibana:
output.logstash:
  hosts: ["logstash01:5044","logstash02:5044","logstash03:5044"]
</pre>

## Context

Yesterdays icingabeat index failed completely and no shard is available anymore. Todays Index is working but Elasticsearchs log is filling up with the following messages:

<pre>
[2018-02-02T09:43:02,924][DEBUG][o.e.a.b.TransportShardBulkAction] [icingabeat-2018.02.02][4] failed to execute bulk item (index) BulkShardRequest [[icingabeat-2018.02.02][4]] containing [index {[icingabeat-2018.02.02][doc][IFCuVWEBKbzJIpsc7RVV], source[n/a, actual length: [44.1kb], max length: 2kb]}]

java.lang.IllegalArgumentException: Limit of total fields [1000] in index [icingabeat-2018.02.02] has been exceeded
</pre>

Having too many distinct fields could lead to "mapping explosion". This is why Elasticsearch doesn't allow more than 1000 distinct fieldnames per Index (no matter if they are nested or not). It seems like about every 5 minutes Icingabeat tries to send a bulk request with a massive count of new fields which gets refused. So the index stays on a healthy count of under 200 fields.

## Your Environment

* Beat version: 6.1.1
* Icinga 2 version: 2.8.1
* Elasticsearch version : 6.1.2
* Logstash version, if used: 6.1.2
* Kibana version, if used: 6.1.2
* Operating System and version: RHEL 7

**Comment by widhalmt** [comment]
It seems that the problem is one of the cluster checks of icinga. Either the configured internal `cluster` check or an output of the API showing every zone with its endpoints as fields including information like if it's connected, it's log lag, etc. With all this extra information about 300 monitored hosts should be sufficient to break the threshold of 1000 distinct fields.

Unfortunately I had to send the logs through Redis and collect them from there. The JSON was unparseable so I had to guess what the exact output is. I can send you the information via email.

**Comment by widhalmt** [comment]
So in short: Icingabeat works as expected but the data it forwards from Icinga is too huge. We have to find a way to keep Icingabeat from sending massive events. Either by splitting them up or, as a first dirty fix, filtering them out.

**Comment by bobapple** [comment]
My solution is to remove the 'zones' key entirely from the statuspoller. Depending on the Icinga configuration it can include a massive amount of data. There are other keys that provide similiar information, such as `conn_endpoints`, `num_conn_endpoints`, `not_conn_endpoints` and so on.
