### ISSUE TITLE
Passwords are sent in clear text to logstash

### ISSUE THREAD

**Issue by joshiegy** [Icinga/icingabeat#22]
## Current Behavior

Output from Icinga with a password is sent unfiltered to Logstash and then show:s up in Kibana.
[check_result][command]: /usr/lib/nagios/plugins/check_mysql, -H, sql.example.org, -p, zhi*!qwdf1234vi<, -u, MyMonitorUser

The field after "-p" should be filtered.
[check_result][command]: /usr/lib/nagios/plugins/check_mysql, -H, sql.example.org, -p, FILTERED_PASSWORD, -u, MyMonitorUser

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Beat version (`icingabeat -version`):
6.1.1
* Icinga 2 version (`icinga2 --version`):
2.8
* Elasticsearch version (`curl -XGET 'localhost:9200'`):
6.2.2
* Logstash version, if used (`bin/logstash -V`):
6.2.2
* Kibana version, if used (`curl -XGET http://localhost:5601/status -I`):
6.2.2
* Operating System and version:
Ubuntu 16

**Comment by bobapple** [comment]
I'm sorry but this cannot be masked by icingabeat. There's no way how I could find the password parameter for all check plugins out there.

**Comment by joshiegy** [comment]
How about a variable in the config. Something like "Filter-pattern"?
filter:
  password_after: ["-p", "-P" ]
  change_to: "Filtered"

And then the first word after "-p" will be changed to "filtered" - would that be possible?

**Comment by dnsmichi** [comment]
Why not send Icingabeat's stream to logstash and filter that over there?
