### ISSUE TITLE
Enable X-Pack Monitoring ?

### ISSUE THREAD

**Issue by MarcusCaepio** [Icinga/icingabeat#23]
Hi,
since Elastic opened the X-Pack and monitoring is now enabled by default and usable with a basic license, how to I enable the monitoring metric for Icingabeat like I do with
`
xpack.monitoring:
  enabled: true
  elasticsearch:
    hosts: [....]
`
in filebeat?

Regards,
Marcus

P.S.: Damn good work guys!

**Comment by bobapple** [comment]
To be honest, I didn't have a chance yet to look into X-Pack yet. I will keep this issue open until I have some time to do icingabeat stuff again

**Comment by MarcusCaepio** [comment]
Just a listening in the monitoring part of kibana would be nice to see that icingabeat is sending data

**Comment by dnsmichi** [comment]
Since you've already looked there, maybe you can create a patch?

**Comment by bobapple** [comment]
The new version `6.3.3` includes the monitoring options. Beat monitoring must be enabled in `icingabeat.yml` by setting `xpack.monitoring.enabled: true`

More options are available, see `icingabeat.reference.yml`
