### ISSUE TITLE
Icingabeat installation on all nodes?

### ISSUE THREAD

**Issue by MarcusCaepio** [Icinga/icingabeat#24]
Hi, 
this is just a question:
In an Icinga2 cluster with 1 Master and X zones with 2 satellite nodes each, is it usefull to install icingabeat on all nodes or just on the master?

**Comment by bobapple** [comment]
Hi @MarcusCaepio 
usually icingabeat is only installed on your master (or on a separate node with access to the Icinga API from the master). The master has all the events and information that icingabeat processes.

**Comment by MarcusCaepio** [comment]
That's what I thought. Thanks
