### ISSUE TITLE
Allow to set target field

### ISSUE THREAD

**Issue by widhalmt** [Icinga/icingabeat#28]
Allow to create all fields from icingabeat as a nested field.

Currently all fields are created under root but some setups want to use nested fields like namespaces so there won't be any collisions between rulesets from different users.

You can use the `target` field of Logstashes `kv` filter.

/ref/NC/545319

**Comment by bobapple** [comment]
I moved all Icinga related fields to an `icinga` group. Since I don't see any use case for a configurable target. Fix is going to be released in 6.5
