### ISSUE TITLE
Export performance data as separate fields

### ISSUE THREAD

**Issue by friesoft** [Icinga/icingabeat#3]
According to docs performancedata is exported in the field "check_result.performance_data" as text.

It would be much cooler to have each perfdata in its own field (check_result.perfdata.size.value), possibly with related fields for thresholds, unit, ...

This would basically allow to get rid of graphite, influxdb, .. and just use the icingabeat + elastic + grafana. I'm currently working on a icingaweb2 module for grafana which could display the graphs from a dashboard using this data.

**Comment by Thomas-Gelf** [comment]
> This would basically allow to get rid of graphite, influxdb, .. and just use the icingabeat + elastic + grafana

Completely OT: be careful with your wishes. I'm not sure whether you wouldn't wish to have those "old" tools back after the first few billion datapoints ;-) And believe me, I'm not a big fan of neither Graphite nor Influx. Apart from that, there is nothing wrong with the feature request itself I guess.

Cheers,
Thomas

**Comment by bobapple** [comment]
The problem with performance data is that they are not structured when received from the API. I would need to parse them in icingabeat. I think parsing of perfdata should be done by Icinga and not by a third party tool. So this will not be part of Icingabeat.

However, @dnsmichi is currently reviewing an Icinga 2 feature that can send parsed perfdata to elasticsearch. I don't know if and when this will come out, it's still work in progress.

**Comment by dnsmichi** [comment]
Details in icinga/icinga#4054
