### ISSUE TITLE
Issue 25/26 in Debian Package?

### ISSUE THREAD

**Issue by viper539** [Icinga/icingabeat#31]
Hello friends,

i currently playing around with icingabeats and installed it following the instruction from the [icinga-website](https://icinga.com/docs/icingabeat/latest/docs/02-installation/) with `apt-get install icingabeat`.

I get many errors like this:
`[2019-02-08T18:23:37,453][WARN ][logstash.outputs.elasticsearch] Could not index event to Elasticsearch. {:status=>400, :action=>["index", {:_id=>nil, :_index=>"logstash-2019.02.08", :_type=>"doc", :routing=>nil}, #<LogStash::Event:0x1a8bc760>], :response=>{"index"=>{"_index"=>"logstash-2019.02.08", "_type"=>"doc", "_id"=>"mUwizmgBuAkVP_3V215q", "status"=>400, "error"=>{"type"=>"mapper_parsing_exception", "reason"=>"object mapping for [host] tried to parse field [host] as object, but found a concrete value"}}}}
`

Debug-output of icingabeats:
`  "@timestamp": "2019-02-08T17:11:40.851Z",
  "@metadata": {
    "beat": "icingabeat",
    "type": "doc",
    "version": "6.5.4"
  },
  "host": {
    "os": {
      "platform": "debian",
      "version": "9 (stretch)",
      "family": "debian",
      "codename": "stretch"
    },
    "id": "ae14dd8d192c433d96d6e2516d507291",
    "containerized": false,
    "name": "icinga",
    "architecture": "x86_64"
  },
  "icinga": {
`and so on...

when i understood issue25 and 26 correct the content of "host" is wrong and was moved to "icingaanything". 
Is it possible that this fix didn't find his way into the debian-package?

Versions: 
icingabeat is running on icingahost Version 6.5.4
ELK on a different Server 6.5.4

Thank you,
Viper539

And BTW: What function has the file: /etc/icingabeats/fields.yml?
It would have been very impressive if you could have solved the error with it.

[edit]: changed URL to installation manual

**Comment by dnsmichi** [comment]
Which version of the package did you install?

**Comment by viper539** [comment]
6.5.4

Am Mo., 11. Feb. 2019 um 09:48 Uhr schrieb Michael Friedrich <
notifications@github.com>:

**Comment by bobapple** [comment]
Checked this, the debian package seems to have the correct code:

```
root@3f0a3d2d0794:/# icingabeat version
icingabeat version 6.5.4 (amd64), libbeat 6.5.4 [cd7d1e09f57f8ad23ca9b7306e62c49de5732758 built 2019-01-03 08:01:31 +0000 UTC]
```
