### ISSUE TITLE
Kibana Dashboards fail to load with icingabeat-7.4.2 and Kibana 7.4

### ISSUE THREAD

**Issue by omarmarquez** [Icinga/icingabeat#34]
## Expected Behavior
New dashboards should be availbale in Kibana

## Current Behavior

`# icingabeat setup kibana
Index setup finished.
Loading dashboards (Kibana must be running and reachable)
Exiting: Failed to import dashboard: Failed to load directory /usr/share/icingabeat/kibana/7/dashboard:
  error loading /usr/share/icingabeat/kibana/7/dashboard/Icingabeat-CheckResults.json: returned 422 to import file: <nil>. Response: {"statusCode":422,"error":"Unprocessable Entity","message":"Document \"a32bdf10-e4be-11e7-b4d1-8383451ae5a4\" has property \"visualization\" which belongs to a more recent version of Kibana (7.4.2)."}
  error loading /usr/share/icingabeat/kibana/7/dashboard/Icingabeat-Notifications.json: returned 422 to import file: <nil>. Response: {"statusCode":422,"error":"Unprocessable Entity","message":"Document \"af54ac40-e4cd-11e7-b4d1-8383451ae5a4\" has property \"visualization\" which belongs to a more recent version of Kibana (7.4.2)."}
  error loading /usr/share/icingabeat/kibana/7/dashboard/Icingabeat-Status.json: returned 422 to import file: <nil>. Response: {"statusCode":422,"error":"Unprocessable Entity","message":"Document \"77052890-e4c0-11e7-b4d1-8383451ae5a4\" has property \"visualization\" which belongs to a more recent version of Kibana (7.4.2)."}

# echo $?
1

`

**Comment by bobapple** [comment]
It looks like it expects Kibana version 7.4.2. Did you try updating your kibana?

**Comment by omarmarquez** [comment]
Correct.
Upgrading to ElasticSerach-7.4.2 fixed all the observed issues.
Thanks!
