### ISSUE TITLE
[trainee task] Make the project a Go module

### ISSUE THREAD

**Issue by Al2Klimov** [Icinga/icingabeat#37]
... w/o the vendored deps.

Don't forget not to work in this repo, but in your fork!

**Comment by bobapple** [comment]
Moving Icingabeat to a Go module does not make sense in my eyes. The project is designed the same way like the official elastic beats. Additinally we rely on the tools to build packages, which require this directory structure.

**Comment by Al2Klimov** [comment]
... and they aren't Go mods, yet?

**Comment by bobapple** [comment]
done with v7.14.2
