### ISSUE TITLE
icingabeat setup command flags not working

### ISSUE THREAD

**Issue by srikar-singam** [Icinga/icingabeat#38]
Able to load dashboards using "icingabeat setup --dashboards -E *data*" but machine learning flag is not creating any ml jobs in Kibana and also it is not even throwing any error.

Can someone tell me why is this flag not working.

**Comment by bobapple** [comment]
There are no ML jobs for icingabeat configured. Are any icingabeat dashboards imported?

**Comment by srikar-singam** [comment]
Okay. Yeah imported 3 dashboards.
