### ISSUE TITLE
Help with host downtime configuration

### ISSUE THREAD

**Issue by rdesanno** [Icinga/icingabeat#6]
I'm trying to query in ES a total number of icinga2 hosts with downtimes set but I am unable to and think its because I am not seeing any data being brought in by icingabeat. Is this a bug or a configuration problem on my end? I'm not making any headway with the documentation and seems light with regard to configuring /etc/icingabeat/icingabeat.yml.

My config is pretty barebones but including it below for reference

grep -v \# /etc/icingabeat/icingabeat.yml | sed -e '/^$/d'
icingabeat:
  host: "XXXXX"
  port: 5665
  user: "XXXXX"
  password: "XXXXX"
  skip_ssl_verify: true
  eventstream:
    types:
      - CheckResult
      - StateChange
      - Notification
      - AcknowledgementSet
      - AcknowledgementCleared
      - CommentAdded
      - CommentRemoved
      - DowntimeAdded
      - DowntimeRemoved
      - DowntimeStarted
      - DowntimeTriggered
    filter: ""
    retry_interval: 10s
  statuspoller:
    interval: 60s
output.elasticsearch:
  hosts: ["XXXXX:9200"]

**Comment by bobapple** [comment]
What does your icingabeat logfile say? Maybe connection issues or API User permissions?

**Comment by rdesanno** [comment]
My server is definitely bogged down but I dont see anything in the logs other than the following error over and over. I expect that this will play some part of my issue but dont understand why my downtime.* fields are not propagating properly.

`2017-03-28T17:17:23-04:00 INFO Bulk item insert failed (i=0, status=429): {"type":"es_rejected_execution_exception","reason":"rejected execution of org.elasticsearch.transport.TransportService$7@5150347 on EsThreadPoolExecutor[bulk, queue capacity = 50, org.elasticsearch.common.util.concurrent.EsThreadPoolExecutor@29cbf70a[Running, pool size = 16, active threads = 16, queued tasks = 50, completed tasks = 279123618]]"}
`
Do I need to do something special before getting fields like downtime.name or downtime.host_name to appear?

**Comment by rdesanno** [comment]
I think its working as intended but my understanding of it is lacking. Closing this issue

**Comment by bobapple** [comment]
Let me know if I can help with something
