### ISSUE TITLE
Minor documenation mistake

### ISSUE THREAD

**Issue by rokka** [Icinga/icingabeat#7]
Url: https://github.com/Icinga/icingabeat

There is a ":" instead "=" in the password line.

object ApiUser "icinga" {
  password: "icinga"
  permissions = ["events/*", "status/query"]
}

=>

object ApiUser "icinga" {
  password = "icinga"
  permissions = ["events/*", "status/query"]
}

**Comment by bobapple** [comment]
@rokka thank you 👍
